### ISSUE TITLE
Mark lal packages as 'broken' on anaconda cloud

### ISSUE THREAD

**Issue by duncanmmacleod** [conda-forge/lal-feedstock#18]
@conda-forge/core, I would appreciate some help in marking the following builds as broken on anaconda.org/conda-forge/ for all platforms:

```
lal          6.18.0  hc3780f3_1
lal          6.18.0  py27hc3780f3_0
lal          6.18.0  py35hc3780f3_0
lal          6.18.0  py36hc3780f3_0
lal          6.18.0  blas_openblash96c67fe_2
lalframe     1.4.3   py27h7eb728f_0
lalframe     1.4.3   py35h7eb728f_0
lalframe     1.4.3   py36h7eb728f_0
python-lal   6.18.0  py27_blas_openblash7eb728f_2
python-lal   6.18.0  py27h7eb728f_1
python-lal   6.18.0  py35_blas_openblash7eb728f_2
python-lal   6.18.0  py35h7eb728f_1
python-lal   6.18.0  py36_blas_openblash7eb728f_2
python-lal   6.18.0  py36h7eb728f_1
```

Many thanks.

**Comment by ocefpaf** [comment]
Done. Can you check and see if I got it right?

https://anaconda.org/conda-forge/lal/files?version=6.18.0&channel=broken

https://anaconda.org/conda-forge/lalframe/files?version=1.4.3&channel=broken

https://anaconda.org/conda-forge/python-lal/files?channel=broken&version=6.18.0

**Comment by duncanmmacleod** [comment]
That looks correct, thanks for the quick turnaround on that. I can still see these packages in `conda search`, is that normal, or am I just being impatient?

**Comment by ocefpaf** [comment]
> I can still see these packages in `conda search`, is that normal, or am I just being impatient?

It can take a while for the index to be updated.

**Comment by duncanmmacleod** [comment]
Ok, thanks.

**Comment by duncanmmacleod** [comment]
Actually, @ocefpaf, it looks like the `lal=6.18=py36hc3780f3_0` builds were missed, can you mark those as well?

**Comment by ocefpaf** [comment]
> Actually, @ocefpaf, it looks like the `lal=6.18=py36hc3780f3_0` builds were missed, can you mark those as well?

I think I got them all now.

https://anaconda.org/conda-forge/lal/files?version=6.18.0

**Comment by duncanmmacleod** [comment]
Thanks again!
